"""
Parse the official Census poverty thresholds into a tracked CSV.

Source file (downloaded to data/raw/xwalk/, which is gitignored):
    https://www2.census.gov/programs-surveys/cps/tables/time-series/
    historical-poverty-thresholds/thresh24.xlsx
    "Poverty Thresholds for 2024 by Size of Family and Number of Related
     Children Under 18 Years", U.S. Census Bureau.

Output (tracked, so the repo is reproducible without the raw download):
    data/processed/poverty_thresholds_2024.csv

The threshold values are parsed out of the spreadsheet. They are never typed in
by hand and never generated by a model -- if the sheet layout changes, this
script fails loudly rather than emitting plausible-looking numbers.

LIMITATION, stated once here and echoed into every scenario's warnings:
family sizes 1 and 2 use the "householder under 65" variant, because the sample
does not carry householder age. This does not touch child poverty (those units
have no children); it slightly overstates poverty among elderly 1-2 person
households.
"""

import pathlib

import pandas as pd

REPO = pathlib.Path(__file__).resolve().parent.parent
SRC = REPO / "data" / "raw" / "xwalk" / "thresh24.xlsx"
OUT = REPO / "data" / "processed" / "poverty_thresholds_2024.csv"

URL = ("https://www2.census.gov/programs-surveys/cps/tables/time-series/"
       "historical-poverty-thresholds/thresh24.xlsx")

# Sheet row index holding each family size. Row 8 is "Under 65 years" for the
# one-person unit; row 12 is "Householder under 65 years" for two people.
SIZE_ROWS = {1: 8, 2: 12, 3: 15, 4: 16, 5: 17, 6: 18, 7: 19, 8: 20, 9: 21}
FIRST_CHILD_COL = 2  # column 2 = zero related children


def main():
    if not SRC.exists():
        raise SystemExit(f"ERROR: {SRC} not found. Download it first:\n  {URL}")
    d = pd.read_excel(SRC, header=None)

    title = str(d.iloc[1, 0])
    if "Poverty Thresholds for 2024" not in title:
        raise SystemExit(f"ERROR: unexpected sheet layout. Row 1 reads: {title!r}\n"
                         "Refusing to parse rather than emit wrong thresholds.")

    recs = []
    for size, r in SIZE_ROWS.items():
        for nkids in range(9):
            v = d.iloc[r, FIRST_CHILD_COL + nkids]
            if pd.notna(v):
                recs.append({"family_size": size,
                             "related_children_under_18": nkids,
                             "threshold_usd": int(v)})
    out = pd.DataFrame(recs)
    if len(out) != 45:
        raise SystemExit(f"ERROR: expected 45 threshold cells, parsed {len(out)}.")

    OUT.parent.mkdir(parents=True, exist_ok=True)
    with open(OUT, "w", newline="", encoding="utf-8") as f:
        f.write("# Official U.S. Census Bureau poverty thresholds for 2024, by family size\n")
        f.write("# and number of related children under 18.\n")
        f.write('# Source: U.S. Census Bureau, "Poverty Thresholds for 2024 by Size of Family\n')
        f.write('#         and Number of Related Children Under 18 Years" (thresh24.xlsx)\n')
        f.write(f"# URL: {URL}\n")
        f.write("# Parsed by model/build_poverty_thresholds.py -- values are NOT hand-typed.\n")
        f.write('# family_size 1 and 2 use the "householder under 65" variant; the sample does\n')
        f.write("# not carry householder age. This does not affect child poverty (those units\n")
        f.write("# have no children) but slightly overstates poverty for elderly 1-2 person units.\n")
        out.to_csv(f, index=False)

    print(out.pivot(index="family_size", columns="related_children_under_18",
                    values="threshold_usd").to_string())
    print(f"\nwrote {OUT.relative_to(REPO)} ({len(out)} cells)")


if __name__ == "__main__":
    main()
