"""
A3 (GATE 1) -- validate the sampled population against published ACS figures.

HOW THE REFERENCE COLUMN IS PRODUCED -- read this, it is the point of the gate.

The published figures in this script are NOT typed in from memory and are NOT
generated by a language model. They are read at runtime out of the Census
Bureau's own ACS 2024 1-Year Table-Based Summary File, downloaded to
data/raw/acs_published/. Each reference value prints with the exact table and
cell id it came from, so any one of them can be clicked through and checked.

    source root: https://www2.census.gov/programs-surveys/acs/summary_file/
                 2024/table-based-SF/data/1YRData/

    B01003_E001  total population (incl. group quarters)
    B11001_E001  total households
    B11002_E001  population living in households
    B11005_E002  households with one or more people under 18
    B19013_E001  median household income

    geography ids: 0100000US = United States
                   0200000US1..4 = Northeast / Midwest / South / West
                   310M700US<cbsa> = metropolitan statistical area

WHY THIS MATTERS: the failure mode this gate exists to catch is a confident but
wrong reference value. A wrong reference makes a broken population look fine,
and every downstream check still passes. Reading the reference straight from
the published file removes that failure mode entirely.

STILL DO THIS BY HAND: pick any two rows below and confirm them yourself at
data.census.gov (search the table id, set year 2024, ACS 1-Year). The script
proves the numbers came out of a Census file; only you can confirm it is the
Census file you meant.

TOLERANCES (from the build plan)
    total households        within 2%
    population in households within 2%
    median household income within 3%
    region shares           within 2 percentage points
"""

from pathlib import Path

import numpy as np
import pandas as pd

REPO = Path(__file__).resolve().parent.parent
PUB = REPO / "data" / "raw" / "acs_published"
PARQUET = REPO / "data" / "processed" / "us_households.parquet"

SRC_URL = ("https://www2.census.gov/programs-surveys/acs/summary_file/2024/"
           "table-based-SF/data/1YRData/acsdt1y2024-{table}.dat")

US = "0100000US"
REGION_GEO = {"Northeast": "0200000US1", "Midwest": "0200000US2",
              "South": "0200000US3", "West": "0200000US4"}
# CBSA codes resolved from the OMB delineation file in build_metro_crosswalk.py.
METRO_CBSA = {"New York": "35620", "Houston": "26420", "Detroit": "19820",
              "San Francisco": "41860", "Phoenix": "38060", "Atlanta": "12060"}


def published(table, cell, geo_id):
    """Read one cell of one geography out of the published summary file."""
    path = PUB / f"{table.lower()}.dat"
    if not path.exists():
        raise SystemExit(f"ERROR: missing {path}. Run the download step in A3 first.")
    df = pd.read_csv(path, sep="|", dtype=str)
    row = df[df["GEO_ID"] == geo_id]
    if row.empty:
        raise SystemExit(f"ERROR: geography {geo_id} not present in {table}.")
    val = row.iloc[0][cell]
    v = float(val)
    # Census uses large negative sentinels for suppressed / not-applicable.
    if v < -100000:
        return np.nan
    return v


def weighted_median(values, weights):
    order = np.argsort(values)
    v, w = np.asarray(values)[order], np.asarray(weights)[order]
    cw = np.cumsum(w) / w.sum()
    return float(v[np.searchsorted(cw, 0.5)])


def row(label, mine, pub, tol_pct=None, tol_pts=None, cite=""):
    if pub is None or (isinstance(pub, float) and np.isnan(pub)):
        return {"label": label, "mine": mine, "pub": np.nan, "diff": np.nan,
                "status": "NO REFERENCE", "cite": cite}
    if tol_pts is not None:
        diff = mine - pub
        ok = abs(diff) <= tol_pts
        return {"label": label, "mine": mine, "pub": pub, "diff": diff,
                "status": "PASS" if ok else "FAIL", "cite": cite, "pts": True}
    diff = 100.0 * (mine - pub) / pub
    ok = abs(diff) <= tol_pct
    return {"label": label, "mine": mine, "pub": pub, "diff": diff,
            "status": "PASS" if ok else "FAIL", "cite": cite}


def print_table(title, rows, fmt="{:,.0f}"):
    print()
    print("=" * 104)
    print(title)
    print("=" * 104)
    print(f"{'measure':<40} {'my weighted est':>18} {'published ACS 2024':>20} "
          f"{'diff':>10}  {'':<8}")
    print("-" * 104)
    for r in rows:
        pub = "  (none)" if np.isnan(r["pub"]) else fmt.format(r["pub"])
        if np.isnan(r["diff"]):
            d = "     n/a"
        elif r.get("pts"):
            d = f"{r['diff']:+.2f} pts"
        else:
            d = f"{r['diff']:+.2f}%"
        print(f"{r['label']:<40} {fmt.format(r['mine']):>18} {pub:>20} {d:>10}  "
              f"{r['status']:<8}")
    print("-" * 104)
    print("sources:")
    for r in rows:
        if r["cite"]:
            print(f"  {r['label']:<38} {r['cite']}")


def main():
    df = pd.read_parquet(PARQUET)
    w = df["design_weight"].to_numpy()
    print(f"Loaded {len(df):,} sampled households from "
          f"{PARQUET.relative_to(REPO)}")
    print(f"Reference files: {PUB.relative_to(REPO)}/  (ACS 2024 1-Year "
          f"Table-Based Summary File)")
    print(f"URL pattern:     {SRC_URL.format(table='<table>')}")

    all_rows = []

    # ------------------------------------------------------------- national
    n_hh = w.sum()
    # Population uses PWGTP-derived person_weight, NOT design_weight * NP.
    # PUMS rakes household and person weights separately; WGTP * NP understates
    # published population by 1.74% nationally. See build_population.py.
    n_pop_hh = df["person_weight"].to_numpy().sum()
    n_children = df["child_weight"].to_numpy().sum()
    med_inc = weighted_median(df["hincp_adj"].to_numpy(), w)
    with_kids = (w * (df["n_children"].to_numpy() > 0)).sum()
    share_kids = 100.0 * with_kids / n_hh

    pub_hh = published("B11001", "B11001_E001", US)
    pub_pop_hh = published("B11002", "B11002_E001", US)
    pub_pop_all = published("B01003", "B01003_E001", US)
    pub_med = published("B19013", "B19013_E001", US)
    pub_kids = published("B11005", "B11005_E002", US)
    pub_children = published("B09001", "B09001_E001", US)
    pub_share_kids = 100.0 * pub_kids / pub_hh

    nat = [
        row("Total households", n_hh, pub_hh, tol_pct=2,
            cite="B11001_E001 @ 0100000US"),
        row("Population living in households", n_pop_hh, pub_pop_hh, tol_pct=2,
            cite="B11002_E001 @ 0100000US"),
        row("Median household income (2024 $)", med_inc, pub_med, tol_pct=3,
            cite="B19013_E001 @ 0100000US"),
        row("Households w/ >=1 person under 18 (%)", share_kids, pub_share_kids,
            tol_pts=2.0, cite="B11005_E002 / B11001_E001 @ 0100000US"),
        row("Children under 18 (population)", n_children, pub_children, tol_pct=2,
            cite="B09001_E001 @ 0100000US"),
    ]
    print_table("NATIONAL", nat, fmt="{:,.1f}")
    all_rows += nat

    print()
    print(f"  note: total population INCLUDING group quarters is "
          f"{pub_pop_all:,.0f} (B01003_E001).")
    print(f"        The sample is a household population by construction "
          f"(group quarters were")
    print(f"        filtered in A2), so it is compared against B11002, not "
          f"B01003. Comparing")
    print(f"        against B01003 would show a spurious "
          f"{100 * (n_pop_hh - pub_pop_all) / pub_pop_all:+.1f}% 'failure'.")
    print()
    print(f"  note: the WRONG estimator sum(design_weight * NP) gives "
          f"{(w * df['NP'].to_numpy()).sum():,.0f}")
    print(f"        ({100 * ((w * df['NP'].to_numpy()).sum() - pub_pop_hh) / pub_pop_hh:+.2f}%). "
          f"It is left in this note deliberately: it passed the")
    print(f"        national 2% tolerance while failing a metro check, which is "
          f"how the bug was found.")

    # --------------------------------------------------------------- region
    reg_rows = []
    for name, geo in REGION_GEO.items():
        mine_share = 100.0 * w[(df["region_name"] == name).to_numpy()].sum() / n_hh
        pub_share = 100.0 * published("B11001", "B11001_E001", geo) / pub_hh
        reg_rows.append(row(f"Household share -- {name} (%)", mine_share,
                            pub_share, tol_pts=2.0,
                            cite=f"B11001_E001 @ {geo} / {US}"))
    print_table("CENSUS REGION DISTRIBUTION (share of households)", reg_rows,
                fmt="{:,.2f}")
    all_rows += reg_rows

    # ---------------------------------------------------------------- metro
    met_rows = []
    for name, cbsa in METRO_CBSA.items():
        geo = f"310M700US{cbsa}"
        m = (df["metro"] == name).to_numpy()
        met_rows.append(row(f"{name} -- households", w[m].sum(),
                            published("B11001", "B11001_E001", geo), tol_pct=5,
                            cite=f"B11001_E001 @ {geo}"))
        met_rows.append(row(f"{name} -- pop in households",
                            df["person_weight"].to_numpy()[m].sum(),
                            published("B11002", "B11002_E001", geo), tol_pct=5,
                            cite=f"B11002_E001 @ {geo}"))
    print_table("METRO AREAS (tolerance 5%: PUMA boundaries do not follow "
                "metro lines exactly)", met_rows)
    all_rows += met_rows

    # -------------------------------------------------------- metro precision
    print()
    print("=" * 104)
    print("METRO SAMPLE SIZE AND PRECISION vs NATIONAL")
    print("=" * 104)
    print(f"{'stratum':<16} {'sample n':>9} {'weighted hh':>14} "
          f"{'sampling frac':>14} {'rel. SE of a 50% share':>24}")
    print("-" * 104)

    def rel_se(n):
        # SE of a proportion at p=0.5, expressed relative to national, is the
        # cleanest single number for "how much wider will my intervals be".
        return 0.5 / np.sqrt(n)

    nat_n = len(df)
    for name in list(METRO_CBSA) + ["rest of US"]:
        m = (df["metro"] == name).to_numpy() if name != "rest of US" \
            else df["metro"].isna().to_numpy()
        n = int(m.sum())
        print(f"{name:<16} {n:>9,} {w[m].sum():>14,.0f} "
              f"{n / m.sum() if False else w[m].sum() / n:>14,.0f} "
              f"{rel_se(n) / rel_se(nat_n):>22.2f}x")
    print(f"{'NATIONAL':<16} {nat_n:>9,} {n_hh:>14,.0f} "
          f"{n_hh / nat_n:>14,.0f} {1.00:>22.2f}x")
    print("-" * 104)
    print("  'sampling frac' column shows households represented per sampled "
          "household.")
    print("  A metro interval is roughly 3.9x wider than the national one at "
          "n=2,000 vs n=30,000.")

    # --------------------------------------------------------------- verdict
    print()
    print("=" * 104)
    fails = [r for r in all_rows if r["status"] == "FAIL"]
    missing = [r for r in all_rows if r["status"] == "NO REFERENCE"]
    if fails:
        print(f"GATE 1: {len(fails)} CHECK(S) FAILED -- STOP. Fix before A4; "
              f"everything downstream inherits this.")
        for r in fails:
            print(f"   FAIL  {r['label']}")
    else:
        print("GATE 1: all automated checks are within tolerance.")
    if missing:
        print(f"  {len(missing)} row(s) had no published reference and were "
              f"left blank rather than guessed.")
    print()
    print("  NOT YET SATISFIED -- the human half of this gate:")
    print("  Open data.census.gov, search table B19013 and table B11001, set")
    print("  year 2024 / ACS 1-Year, geography United States, and confirm two")
    print("  of the published values above with your own eyes. This script can")
    print("  prove the numbers came from a Census file; it cannot prove it is")
    print("  the right Census file.")
    print("=" * 104)


if __name__ == "__main__":
    main()
